### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#128]
- [ ] Rename master to main
- [ ] Get rid of `NoType`
- [ ] Switch from `NullableType` to `NonNullType`
- [ ] Move to CE3
- [ ] Cross build for Scala 3
- [ ] Rework SQL compiler

**Comment by tpolecat** [comment]
I think we probably need to get the doc site back in shape as well.

**Comment by tpolecat** [comment]
Also need to implement subscriptions (in progress).

**Comment by milessabin** [comment]
I'm about to land a second rewrite of the SQL compiler.

**Comment by milessabin** [comment]
Cross-building for Scala.js makes sense ... I'll add it to the list.

Point taken about unstable dependencies. The core module doesn't have any unstable dependencies, so maybe we declare 1.0.0 for core, and have the circe/doobie/skunk module versions track the corresponding upstream versions?

**Comment by armanbilge** [comment]
Huh, core also seems to depend on circe, as well as cats-parse.

https://github.com/gemini-hlsw/gsp-graphql/blob/79f2b1cc9e2f541b203d2902014f173bfaa5447a/build.sbt#L84-L100

**Comment by milessabin** [comment]
Hmm ... that could probably be eliminated. It's only used internally, mainly to generate result Json, and it's probably not the most efficient way of doing that, so a faster, stable, alternative might be a better option.

**Comment by milessabin** [comment]
@armanbilge added a couple of issues to reflect your comments: #202, #203.

**Comment by milessabin** [comment]
@armanbilge I think we have to stick with cats-parse. I think on balance I'd be happy to bump Grackle's major version number if we need to updates cats-parse before it reaches 1.0.0.

**Comment by jbotto94** [comment]
Hi,
I'm always looking for open source things to work on and I'd like to help out. Would anyone mind if I worked on #197 or #199? I'm more than happy to look at any other small/self contained issues that might be more useful/appropriate.

**Comment by milessabin** [comment]
@jbotto94 sorry, I missed your message earlier. Both #197 and #199 are real chores and a bit fiddly ... I wouldn't want to inflict them on you. How about #237? It involves digging around in the query algebra and the various places it's used ... I think it'll be a lot more interesting and give more insight into how Grackle hangs together.

**Comment by jbotto94** [comment]
> @jbotto94 sorry, I missed your message earlier. Both #197 and #199 are real chores and a bit fiddly ... I wouldn't want to inflict them on you. How about #237? It involves digging around in the query algebra and the various places it's used ... I think it'll be a lot more interesting and give more insight into how Grackle hangs together.

Sure :). Wasn't sure if you had started working on it or not.

**Comment by armanbilge** [comment]
@milessabin here's another one to add to the list: you should probably replace the log4cats-slf4j dependency with just log4cats-core and ask for a `LoggerFactory` constraint. Users can them import an implicit `Slf4jLoggerFactory` to satisfy it.

https://github.com/gemini-hlsw/gsp-graphql/blob/6d4223acc817de01c13e32e75091d6f6712835f3/build.sbt#L125

A few motivating reasons:
1. slf4j recently released a 2.0 and the implications are not yet clear. Dodging the dependency altogether is a good strategy.
2. There maybe be other log4cats backends in the near future, such as [otel4s](https://github.com/typelevel/otel4s).
3. slf4j is not available for Scala.js or Scala Native. Depending on it will force that code to be split when we cross-compile.

**Comment by milessabin** [comment]
@armanbilge I _think_ `log4cats-slf4j` should only be a test dependency.

**Comment by milessabin** [comment]
@armanbilge apropos SLF4J, see #404.

**Comment by milessabin** [comment]
We're pretty much done! :tada:

I do want to get #258 in as well though.
