### ISSUE TITLE
Spec coverage checklist

### ISSUE THREAD

**Issue by milessabin** [gemini-hlsw/gsp-graphql#8]
Current coverage of the [GraphQL Specification, June 2018](https://graphql.github.io/graphql-spec/June2018/).

- [x] 2 Language
  - [x] 2.1 Source Text
    - [x] 2.1.1 Unicode
    - [x] 2.1.2 White Space
    - [x] 2.1.3 Line Terminators
    - [ ] 2.1.4 Comments
    - [ ] 2.1.5 Insignificant Commas
    - [x] 2.1.6 Lexical Tokens
    - [ ] 2.1.7 Ignored Tokens
    - [x] 2.1.8 Punctuators
    - [x] 2.1.9 Names
  - [x] 2.2 Document
  - [x] 2.3 Operations
  - [x] 2.4 Selection Sets
  - [x] 2.5 Fields
  - [x] 2.6 Arguments
  - [ ] 2.7 Field Alias
  - [x] 2.8 Fragments
    - [x] 2.8.1 Type Conditions
    - [x] 2.8.2 Inline Fragments
  - [x] 2.9 Input Values
    - [x] 2.9.1 Int Value
    - [x] 2.9.2 Float Value
    - [x] 2.9.3 Boolean Value
    - [x] 2.9.4 String Value
    - [ ] 2.9.5 Null Value
    - [x] 2.9.6 Enum Value
    - [ ] 2.9.7 List Value
    - [ ] 2.9.8 Input Object Values
  - [ ] 2.10 Variables
  - [x] 2.11 Type References
  - [ ] 2.12 Directives
- [x] 3 Type System
  - [ ] 3.1 Type System Extensions
  - [x] 3.2 Schema
    - [x] 3.2.1 Root Operation Types
    - [ ] 3.2.2 Schema Extension
  - [x] 3.3 Descriptions
  - [x] 3.4 Types
    - [x] 3.4.1 Wrapping Types
    - [x] 3.4.2 Input and Output Types
    - [ ] 3.4.3 Type Extensions
  - [x] 3.5 Scalars
    - [x] 3.5.1 Int
    - [x] 3.5.2 Float
    - [x] 3.5.3 String
    - [x] 3.5.4 Boolean
    - [x] 3.5.5 ID
    - [ ] 3.5.6 Scalar Extensions
  - [x] 3.6 Objects
    - [x] 3.6.1 Field Arguments
    - [x] 3.6.2 Field Deprecation
    - [ ] 3.6.3 Object Extensions
  - [x] 3.7 Interfaces
    - [ ] 3.7.1 Interface Extensions
  - [x] 3.8 Unions
    - [ ] 3.8.1 Union Extensions
  - [x] 3.9 Enums
    - [ ] 3.9.1 Enum Extensions
  - [ ] 3.10 Input Objects
    - [ ] 3.10.1 Input Object Extensions
  - [x] 3.11 List
  - [x] 3.12 Non-Null
    - [x] 3.12.1 Combining List and Non-Null
  - [ ] 3.13 Directives
    - [ ] 3.13.1 @skip
    - [ ] 3.13.2 @include
    - [ ] 3.13.3 @deprecated
- [x] 4 Introspection
  - [x] 4.1 Reserved Names
  - [x] 4.2 Documentation
  - [x] 4.3 Deprecation
  - [x] 4.4 Type Name Introspection
  - [x] 4.5 Schema Introspection
    - [x] 4.5.1 The __Type Type
    - [x] 4.5.2 Type Kinds
      - [x] 4.5.2.1 Scalar
      - [x] 4.5.2.2 Object
      - [x] 4.5.2.3 Union
      - [x] 4.5.2.4 Interface
      - [x] 4.5.2.5 Enum
      - [x] 4.5.2.6 Input Object
      - [x] 4.5.2.7 List
      - [x] 4.5.2.8 Non-Null
    - [x] 4.5.3 The __Field Type
    - [x] 4.5.4 The __InputValue Type
    - [x] 4.5.5 The __EnumValue Type
    - [x] 4.5.6 The __Directive Type
- [x] 5 Validation
  - [x] 5.1 Documents
    - [x] 5.1.1 Executable Definitions
  - [x] 5.2 Operations
    - [x] 5.2.1 Named Operation Definitions
      - [x] 5.2.1.1 Operation Name Uniqueness
    - [x] 5.2.2 Anonymous Operation Definitions
      - [x] 5.2.2.1 Lone Anonymous Operation
    - [ ] 5.2.3 Subscription Operation Definitions
      - [ ] 5.2.3.1 Single root field
  - [x] 5.3 Fields
    - [x] 5.3.1 Field Selections on Objects, Interfaces, and Unions Types
    - [ ] 5.3.2 Field Selection Merging
    - [x] 5.3.3 Leaf Field Selections
  - [x] 5.4 Arguments
    - [x] 5.4.1 Argument Names
    - [x] 5.4.2 Argument Uniqueness
      - [x] 5.4.2.1 Required Arguments
  - [x] 5.5 Fragments
    - [x] 5.5.1 Fragment Declarations
      - [x] 5.5.1.1 Fragment Name Uniqueness
      - [x] 5.5.1.2 Fragment Spread Type Existence
      - [x] 5.5.1.3 Fragments On Composite Types
      - [ ] 5.5.1.4 Fragments Must Be Used
    - [x] 5.5.2 Fragment Spreads
      - [x] 5.5.2.1 Fragment spread target defined
      - [ ] 5.5.2.2 Fragment spreads must not form cycles
      - [x] 5.5.2.3 Fragment spread is possible
        - [ ] 5.5.2.3.1 Object Spreads In Object Scope
        - [ ] 5.5.2.3.2 Abstract Spreads in Object Scope
        - [ ] 5.5.2.3.3 Object Spreads In Abstract Scope
        - [ ] 5.5.2.3.4 Abstract Spreads in Abstract Scope
  - [x] 5.6 Values
    - [x] 5.6.1 Values of Correct Type
    - [ ] 5.6.2 Input Object Field Names
    - [ ] 5.6.3 Input Object Field Uniqueness
    - [ ] 5.6.4 Input Object Required Fields
  - [ ] 5.7 Directives
    - [ ] 5.7.1 Directives Are Defined
    - [ ] 5.7.2 Directives Are In Valid Locations
    - [ ] 5.7.3 Directives Are Unique Per Location
  - [ ] 5.8 Variables
    - [ ] 5.8.1 Variable Uniqueness
    - [ ] 5.8.2 Variables Are Input Types
    - [ ] 5.8.3 All Variable Uses Defined
    - [ ] 5.8.4 All Variables Used
    - [ ] 5.8.5 All Variable Usages are Allowed
- [x] 6 Execution
  - [x] 6.1 Executing Requests
    - [ ] 6.1.1 Validating Requests
    - [x] 6.1.2 Coercing Variable Values
  - [x] 6.2 Executing Operations
    - [x] 6.2.1 Query
    - [ ] 6.2.2 Mutation
    - [ ] 6.2.3 Subscription
      - [ ] 6.2.3.1 Source Stream
      - [ ] 6.2.3.2 Response Stream
      - [ ] 6.2.3.3 Unsubscribe
  - [x] 6.3 Executing Selection Sets
    - [ ] 6.3.1 Normal and Serial Execution
    - [x] 6.3.2 Field Collection
  - [x] 6.4 Executing Fields
    - [x] 6.4.1 Coercing Field Arguments
    - [x] 6.4.2 Value Resolution
    - [x] 6.4.3 Value Completion
    - [x] 6.4.4 Errors and Non-Nullability
- [x] 7 Response
  - [x] 7.1 Response Format
    - [x] 7.1.1 Data
    - [x] 7.1.2 Errors
  - [x] 7.2 Serialization Format
    - [x] 7.2.1 JSON Serialization
    - [x] 7.2.2 Serialized Map Ordering
